package com.bossed.waej.javebean

data class ShopMsgBean(
    val code: Int,
    val `data`: ShopMsgData,
    val msg: String
)

data class ShopMsgData(
    val address: String,
    val browseCount: Int,
    val businessBegin: String,
    val businessEnd: String,
    val businessIntroduction: String,
    val businessLicense: String,
    val businessStatus: Int,
    val businessTime: String,
    val city: String,
    val contactName: String,
    val contactPhone: String,
    val county: String,
    val deviceDescription: String,
    val doorPhoto: String,
    val entryTime: String,
    val followCount: Int,
    val freecheckitems: String,
    val fullname: String,
    val id: Int,
    val idCardBack: String,
    val idCardFront: String,
    val isDefault: Int,
    val latitude: String,
    val longitude: String,
    val madeFeeRate: Float,
    val madeRate: Float,
    val madeType: Int,
    val mainModels: String,
    val operationStation: Int,
    val praseCount: Int,
    val promise: String,
    val promotion: String,
    val province: String,
    val rejectCause: String,
    val score: Int,
    val shopDescription: String,
    val shopMiniQrcode: String,
    val shopNumber: String,
    val shopPhone: String,
    val shopTrade: String,
    val shopType: String,
    val withdrawalAccount: String,
    val shopkeeperId: Int,
    val status: Int,
    val tags: String,
    val kmShopImageVoList: List<KmShopImageVoListBean>,
    val technicianNum: Int
)